### ISSUE TITLE
Missing files for code in Clinvar folder

### ISSUE THREAD

**Issue by ys196** [ruth-hanna/base-editor-screen-analysis#1]
Hi, 

I'm trying to test out the code in the Clinvar folder, but found that these input files are missing: 

lfcs = pd.read_csv('../Data/Filtered_LFC_files/ClinVar_AADW08_filtered_v1.csv')
# library annotations for describing designs
unfiltered_annotations = pd.read_csv('../Data/Annotations/ClinVar_GC/AADW08_annotation_v1.csv')
snp_annotations = pd.read_csv('../Data/Annotations/ClinVar_GC/snp_df_Full_Library_new_variants.txt', 
                             sep = '\t')
vep_annotations = pd.read_csv('../Data/Annotations/ClinVar_GC/clinvar_gc_filtered_CT_VEP_annotation_2020-03-16_v1.txt', 
                          sep = '\t')
essential_genes = pd.read_csv('../Data/Annotations/ClinVar_GC/hart_essential_genes.txt', sep = '\t')
brca1 = pd.read_csv('../Data/Filtered_LFC_files/BRCA1_AAEG04_RDA256_filtered_v6.csv')
brca2 = pd.read_csv('../Data/Filtered_LFC_files/BRCA2_AAEG05_RDA256_filtered_v6.csv')

I guess some or all of them have equivalent part in the output tables from the Screening_Data_Preprocessing notebook.  However, I can't figure out which part is which.  Would you be able to help me out or add the input files here?  Thanks!

Best,

Sunny

**Comment by ruth-hanna** [comment]
Hi Sunny,

Thank you for reaching out and I apologize for the delay - I had to track
down the appropriate files.

I've uploaded the files to Figshare at the following links:
https://figshare.com/articles/dataset/Filtered_LFC_files/19140497
<goog_1324936587>
https://figshare.com/articles/dataset/Annotations/19140482

The "Filtered_LFC_files" have slightly different names since we renamed
things prior to publication. The correspondence is as follows:
ClinVar_AADW08_filtered_v1.csv --> Table_S10_filtered_BE3_v1.csv
BRCA1_AAEG04_RDA256_filtered_v6.csv --> Table_S2_filtered_BRCA1_v1.csv
BRCA2_AAEG05_RDA256_filtered_v6.csv --> Table_S2_filtered_BRCA2_v1.csv

There may be some slight differences in the annotation columns that are
included but the data is the same. I think it should be pretty
self-explanatory, but if you run into any issues I can send you the
original versions as well.

Best,
Ruth

**Comment by ys196** [comment]
Hi, Ruth,

Thank you very much for tracking down these files.  

Best,

Sunny
